// <auto-generated />
namespace PhotoBook.DAL.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class RatingTbl : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RatingTbl));
        
        string IMigrationMetadata.Id
        {
            get { return "201312022217484_RatingTbl"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
