// <auto-generated />
namespace PhotoBook.DAL.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class RatingTypeChanged2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RatingTypeChanged2));
        
        string IMigrationMetadata.Id
        {
            get { return "201311081833521_RatingTypeChanged2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
