// <auto-generated />
namespace PhotoBook.DAL.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class RatingTypeChanged : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RatingTypeChanged));
        
        string IMigrationMetadata.Id
        {
            get { return "201311081833094_RatingTypeChanged"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
